<script lang="ts">
	import { OverlayScrollbarsComponent } from 'overlayscrollbars-svelte';
	import * as v from 'valibot';

	import { asset } from '$app/paths';
	import { page } from '$app/state';

	import { alert } from '$lib/components/alert.svelte';
	import { validate } from '$lib/components/parts/validate.svelte';
	import Translation from '$lib/components/translation.svelte';
	import { tr } from '$lib/i18n.svelte';

	import { doImport } from './import';
	import { ImportUrlScheme, QUERY_SUMMON_URL_BASE } from './validation';

	interface Props {
		onopen: () => void;
		onclose: () => void;
	}

	const props: Props = $props();

	let url = $state('');

	const handleImport = async (event: Event) => {
		event.preventDefault();

		// TODO: show loading status
		const result = await doImport(url);

		props.onclose();

		alert(
			result.error
				? tr({
						zh: `导入失败：${result.error}`,
						en: `Import failed: ${result.error}`,
					})
				: tr({
						zh: `导入完成，新增 ${result.imported} 条记录`,
						en: `Import completed. Added ${result.imported} new records`,
					}),
		);

		if (!result.error) {
			props.onopen();
		}
	};

	let selectedPlatform = $state('macOS');
</script>

<OverlayScrollbarsComponent
	defer
	class="w-full h-full os-toplevel-y"
	options={{ scrollbars: { autoHide: 'scroll' } }}
>
	<h3 class="font-medium text-ml text-gray-600 p-3 text-center">
		{tr({ zh: '导入征集记录', en: 'Import Summon History' })}
	</h3>

	<form onsubmit={handleImport}>
		<label class="block border-y border-gray-300">
			<p class="sr-only">{tr({ zh: '导入地址', en: 'Import URL' })}</p>
			<textarea
				name="url"
				rows="3"
				class="block w-full text-sm border-0 ring-0 bg-transparent resize-none break-all"
				placeholder={`${QUERY_SUMMON_URL_BASE}?userId=...`}
				bind:value={url}
				use:validate={v.message(ImportUrlScheme, tr({ zh: '地址无效', en: 'Invalid URL' }))}
				autocomplete="off"
				// I have no clue why 1password show username suggestions here
				data-1p-ignore
			></textarea>
		</label>

		<div class="flex flex-row items-center justify-end gap-2 pl-2">
			<button class="btn btn-inlay border-l">{tr({ zh: '导入', en: 'Import' })}</button>
		</div>
	</form>

	<div class="h-2.5 border-y border-gray-300 bg-stripe"></div>

	<section class="flex flex-row items-stretch text-ms p-1 gap-1 text-gray-500">
		{#each ['macOS', 'Windows', 'iOS', 'Android'] as platform (platform)}
			<button
				class="py-1 flex-1 cursor-pointer rounded-xs ring-inset ring-gray-200"
				class:ring-1={selectedPlatform === platform}
				class:bg-white={selectedPlatform === platform}
				onclick={() => (selectedPlatform = platform)}
			>
				{platform}
			</button>
		{/each}
	</section>

	<section class="p-3 text-ms text-gray-600 border-t border-gray-300 space-y-2">
		{#if selectedPlatform === 'macOS'}
			<Translation>
				{#snippet zh()}
					<p class="font-medium">
						该方式适用于从 App Store 或用 PlayCover 安装的游戏。Android 模拟器请使用适用于 Android
						平台的方式。
					</p>
					<p>在终端内运行以下命令：</p>
				{/snippet}
				{#snippet en()}
					<p class="font-medium">
						This method is for games installed from App Store or with PlayCover. Games installed in
						Android emulators should use the method for Android.
					</p>
					<p>Run the following command in your terminal:</p>
				{/snippet}
			</Translation>

			<div class="bg-gray-400/10 rounded py-2 px-3 text-sm">
				<pre class="whitespace-normal break-all">curl -fsSL {page.url.origin}{asset('/summon/macos.sh')} | bash</pre>
			</div>
		{:else if selectedPlatform === 'Windows'}
			<p>
				{tr({ zh: '参见：', en: 'See: ' })}<a
					href="https://www.timekeeper.top/auto_import.html"
					target="_blank"
					rel="external noopener noreferrer"
					class="text-link"
				>https://www.timekeeper.top/auto_import.html</a>
			</p>
		{:else}
			<p class="mb-0.5">{tr({ zh: '参见：', en: 'See: ' })}</p>
			<ul class="list-disc ml-3.75 space-y-0.5">
				<li>
					<a
						href="https://mp.weixin.qq.com/s/bKMB42_hl8uLgWxUvLVQtQ"
						target="_blank"
						rel="external noopener noreferrer"
						class="text-link"
					>https://mp.weixin.qq.com/s/bKMB42_hl8uLgWxUvLVQtQ</a>
				</li>
				<li>
					<a
						href="https://mp.weixin.qq.com/s/LcH2a2FYdq_yX379haodPA"
						target="_blank"
						rel="external noopener noreferrer"
						class="text-link"
					>https://mp.weixin.qq.com/s/LcH2a2FYdq_yX379haodPA</a>
				</li>
			</ul>
		{/if}

		<p>
			<Translation
				zh="游戏生成的征集回顾地址很快就会过期失效。如果在导入时提示「没有权限」，请退出征集界面或重启游戏，然后重新打开征集回顾，并立刻尝试获取地址与导入。"
				en="The Summon History URL generated by the game will expire very soon. If you see an error, exit the Summon UI or restart the game. Then reopen the Summon History, retrieve the URL, and try importing it immediately."
			/>
		</p>
	</section>
</OverlayScrollbarsComponent>
